### ISSUE TITLE
Uncaught TypeError: Cannot read property 'TableEditor' of undefined

### ISSUE THREAD

**Issue by jennalanger** [forivall/atom-tablr-json#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [tablr-json](https://github.com/forivall/atom-tablr-json) package 0.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'TableEditor' of undefined

```
At /Users/langer/.atom/packages/tablr-json/lib/tablr-json.js:60

TypeError: Cannot read property 'TableEditor' of undefined
    at TablrJson.open (/packages/tablr-json/lib/tablr-json.js:60:59)
    at HTMLElement.tablrJsonOpen (/packages/tablr-json/lib/tablr-json.js:17:37)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347765)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725071)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:732994)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -0:13.1.0 tablr-json:open (input.hidden-input)
```

### Non-Core Packages

```
geo-editor 0.2.1 
jsonlint 1.1.4 
tablr-json 0.1.1 
```

**Comment by forivall** [comment]
You need the [tablr](https://github.com/abe33/atom-tablr) package for this package to work
